[package]
name = "jws"
version = "0.1.0"
authors = ["Glade Miller <glade.miller@insidesales.com>"]

[dependencies]
time = "*"
serde = "0.8"
serde_json = "0.8"
openssl = "0.7.13"
rustc-serialize = "0.3"
rand = "*"
quick-error = "*"
